package mlx

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/orchestra-hq/atlas/internal/core"
)

// Generation (Execute/ExecuteStream) and core⇄OpenAI translation are tested in
// internal/engines/openaichat, the shared layer this adapter embeds. These tests
// cover only the MLX-specific behavior: CountTokens via a one-token completion
// probe (mlx_lm.server has no /tokenize), and ContextWindow served from the
// catalog window (mlx_lm.server's /v1/models reports no length).

func TestCountTokensViaProbe(t *testing.T) {
	var got struct {
		Model     string `json:"model"`
		MaxTokens int    `json:"max_tokens"`
		Messages  []struct {
			Role string `json:"role"`
		} `json:"messages"`
	}
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/v1/chat/completions" {
			t.Errorf("unexpected path %q", r.URL.Path)
		}
		raw, _ := io.ReadAll(r.Body)
		_ = json.Unmarshal(raw, &got)
		w.Header().Set("content-type", "application/json")
		// mlx_lm.server returns usage.prompt_tokens; one completion token is
		// generated by the probe and must not affect the prompt count.
		_, _ = io.WriteString(w, `{"choices":[{"message":{"content":"x"},"finish_reason":"length"}],"usage":{"prompt_tokens":41,"completion_tokens":1}}`)
	}))
	defer srv.Close()

	a := New(srv.URL, "mlx-community/Some-Model-4bit", 8192, true, srv.Client())
	n, err := a.CountTokens(context.Background(), core.Request{
		Model:     "logical-name", // ignored: the adapter echoes the loaded repo id
		System:    "be terse",
		Messages:  []core.Message{{Role: core.RoleUser, Blocks: []core.ContentBlock{core.TextBlock("hi")}}},
		MaxTokens: 512,
	})
	if err != nil {
		t.Fatalf("CountTokens: %v", err)
	}
	if n != 41 {
		t.Errorf("count = %d, want 41 (usage.prompt_tokens)", n)
	}
	// The probe must cap generation at one token, and echo the loaded repo id (not
	// the request's logical model) so mlx_lm.server serves rather than tries to load
	// a new repo.
	if got.MaxTokens != 1 {
		t.Errorf("probe max_tokens = %d, want 1", got.MaxTokens)
	}
	if got.Model != "mlx-community/Some-Model-4bit" {
		t.Errorf("probe model = %q, want the loaded repo id", got.Model)
	}
	if len(got.Messages) != 2 || got.Messages[0].Role != "system" {
		t.Errorf("probe messages = %+v, want system + user", got.Messages)
	}
}

func TestContextWindowFromCatalog(t *testing.T) {
	// No server should be contacted — ContextWindow is answered from the catalog
	// value the adapter was built with.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		t.Error("ContextWindow must not call the engine")
		w.WriteHeader(http.StatusInternalServerError)
	}))
	defer srv.Close()

	a := New(srv.URL, "repo", 16384, true, srv.Client())
	n, err := a.ContextWindow(context.Background())
	if err != nil {
		t.Fatalf("ContextWindow: %v", err)
	}
	if n != 16384 {
		t.Errorf("context window = %d, want 16384 (catalog value)", n)
	}
}

func TestContextWindowUnknownIsZero(t *testing.T) {
	a := New("http://127.0.0.1:0", "repo", 0, true, http.DefaultClient)
	n, err := a.ContextWindow(context.Background())
	if err != nil {
		t.Fatalf("ContextWindow: %v", err)
	}
	if n != 0 {
		t.Errorf("context window = %d, want 0 (unknown → fit assertion skipped)", n)
	}
}
